---

# tasks to install ansible-meld
# INFO larger roles should only use **include_tasks** here


# INFO This task may be obsolete for your use-case
- name: Gather package facts
  ansible.builtin.package_facts:

- name: Include dependencies
  ansible.builtin.include_tasks:
    file: dependencies.yml

- name: Install meld
  become: true
  when: meld_package not in ansible_facts.packages
  ansible.builtin.package:
    name: "{{ meld_package }}"
    state: present

- name: Configure meld settings
  loop: "{{ meld_settings | dict2items }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"

- name: Add meld to gnome favorites
  when: gnome_favorite
  ansible.builtin.include_tasks:
    file: favorite.yml

...
